export const AppConfig = {
  site_name: 'SHRI SANT GOROBA KAKA NAGARI SAHAKARI CREDIT SOCIETY LTD.',
  title: 'SHRI SANT GOROBA KAKA NAGARI SAHAKARI CREDIT SOCIETY LTD.',
  description: 'SHRI SANT GOROBA KAKA NAGARI SAHAKARI CREDIT SOCIETY LTD.',
  locale: 'en',
};
